- name: Set up local terminal environment
  hosts: local
  roles:
    - role: zsh
      tags: ['zsh']
    - role: oh-my-zsh
      tags: ['oh-my-zsh']
    - role: powerlevel10k
      tags: ['powerlevel10k']
    - role: zsh-dircolors-solarized
      tags: ['zsh-dircolors-solarized']
    - role: zsh-autosuggestions
      tags: ['zsh-autosuggestions']
    - role: zsh-syntax-highlighting
      tags: ['zsh-syntax-highlighting']
    - role: tmux
      tags: ['tmux']
    - role: fzf
      tags: ['fzf']
    - role: neovim
      tags: ['neovim']
    - role: cspell
      tags: ['cspell']
    - role: kubernetes-tools
      tags: ['k8s-tools']
    - role: iterm2
      tags: ['iterm2']
      when: ansible_os_family == 'Darwin'
